2025-01-08 07:08:31,291 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for kevalsite
2025-01-08 07:08:31,307 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for kevalsite
2025-01-08 07:08:31,322 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for kevalsite
2025-01-08 07:08:31,904 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for kevalsite
2025-01-08 07:08:31,931 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for kevalsite
2025-01-08 11:16:13,547 ERROR scheduler Exception in Enqueue Events for Site newsite
Traceback (most recent call last):
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 117, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 130, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/__init__.py", line 1370, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/model/meta.py", line 63, in get_meta
    meta = Meta(doctype)
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/__init__.py", line 655, in throw
    msgprint(
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/__init__.py", line 620, in msgprint
    _raise_exception()
  File "/home/hp/Desktop/office_work/Office_work/frappe-bench/apps/frappe/frappe/__init__.py", line 571, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: DocType System Settings not found
